### ISSUE TITLE
There may be an error in Search.ino

### ISSUE THREAD

**Issue by todosko** [mathieucarbou/MycilaPZEM004Tv3#4]
I also found that in your example Search.ino the program finds 2 devices.
Although only one is connected...
Result:
Found 2 devices
Address: 0x0A
Address: 0xF8 - ???

**Comment by mathieucarbou** [comment]
it does not find 2 devices.

`0xF8` is the default address used when no address is given. Any PZEM, whether it was assigned  an address or not can be reached with this address.

Slave addresses start at `0x01` up to `0xF7` which gives `0xF7` addresses total for slave addresses.

`0xF8` reaches every PZEM so you should at least have.

`MYCILA_PZEM_MAX_ADDRESS_COUNT` is set to `0xF8`, because the max address count is indeed `0xF8`, including save addresses and default address.

If you need to remove the default adresse and only search for slave addresses, then your maxCount should be `MYCILA_PZEM_MAX_ADDRESS_COUNT - 1`

Please have a look at the source header and doc and eventually cpp code for more detail and if you think there is more let me know.

But I would advise to learn more about PZEM addresses - this would have answered your question I guess. `0xF8` is special ;-)
